name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ^12.9.0

      - name: Install npm@7
        run: npm install -g npm@7

      - name: Install Dependencies
        run: npm ci

      - name: Prepare release build
        run: |
          export "RELEASE_TAG=${GITHUB_REF#refs/*/}"
          export "RELEASE_VERSION=${RELEASE_TAG:1}"

          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

          echo "See full release notes at: https://github.com/mongodb-js/vscode/releases/tag/${RELEASE_TAG}\n" > CHANGELOG.md
          npx json -I -f package.json -e "this.version='${RELEASE_VERSION}'"
          npx json -I -f package-lock.json -e "this.version='${RELEASE_VERSION}'"
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build vsxi
        # TODO: replace with real build
        run: |
          cat CHANGELOG.md
          cat package.json
          cat package-lock.json
          echo 'Replace this with a real build!' > fake.vsxi

      - name: Create Draft Release
        run: |
          echo Creating draft release for: "${RELEASE_TAG}"
          gh release create "${RELEASE_TAG}" \
            --title "${RELEASE_TAG}" \
            --notes "Edit the release notes before publishing." \
            --target main \
            --draft \
            *.vsxi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
