name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download release assets
        run: |
          echo Running!
