name: Rebuild changelog

on:
  release:
    types: [published]
  # Once a week or on pushes to main
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches:
      - main

jobs:
  update_generated_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
    #   - uses: actions/setup-node@v2
    #     with:
    #       node-version: ^12.9.0

    #   - name: Install npm@7
    #     run: npm install -g npm@7

    #   - name: Set up Git
    #     run: |
    #       git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #       git config --local user.name "github-actions[bot]"

      - name: Update CHANGELOG.md
        run: |
          echo "# Change Log" > CHANGELOG.md
          echo "" >> CHANGELOG.md

          gh release list | while read line; do
            tagName=$(echo $line | awk '{ print $3 }')
            echo "line: $line --- tag: $tagName"

            json=$(gh release view $tagName --json=name,publishedAt,url,body)
            url=$(echo $json | jq .url)
            name=$(echo $json | jq .name)
            date=$(echo $json | jq .publishedAt | cut -f1 -dT)
            body=$(echo $json | jq .body)
            echo "## [$name]($url) - $date" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "$body"
            echo "" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          done

          cat CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #   run: npm run update-third-party-notices

      # - name: Commit THIRD-PARTY-NOTICES changes
      #   run: |
      #     git add THIRD-PARTY-NOTICES.md
      #     git commit --no-allow-empty -m "chore: update THIRD-PARTY-NOTICES" THIRD-PARTY-NOTICES.md || true

      # - name: Update AUTHORS
      #   run: npm run update-authors
      # - name: Commit AUTHORS changes
      #   run: |
      #     git add AUTHORS
      #     git commit --no-allow-empty -m "chore: update AUTHORS" AUTHORS || true
      # - name: Push updates
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main