name: Main

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ^12.9.0

      - name: Install npm@7
        run: npm install -g npm@7

      - name: Install Dependencies
        run: npm ci

      - name: Prepare release build
        run: |
          export "RELEASE_VERSION=${GITHUB_REF#refs/*/}"
          echo "See full release notes at: https://github.com/mongodb-js/vscode/releases/tag/${RELEASE_VERSION}" > CHANGELOG.md
          npx json -I -f package.json -e "this.version='${RELEASE_VERSION}'"
          npx json -I -f package-lock.json -e "this.version='${RELEASE_VERSION}'"

          cat CHANGELOG.md
          cat package.json
          cat package-lock.json

        if: startsWith(github.ref, 'refs/tags/')

      - name: Release Notes
        uses: mikepenz/release-changelog-builder-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          draft: true
          files: |
            *.vsxi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
